---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketingworker-configmap
  namespace: default
data:
  MessagingQueue: "ticketing.worker"
  MessagingUsername: "user"
  MessagingPassword: "hdTPkyClUB"
  Messaging: "quiet-narwhal-rabbitmq.default.svc.cluster.local"
  WorkerName: "K8S_WORKER"
  SignalR: "http://ticketingweb/workers"
---
