apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ticketingworker
  namespace: default
  labels:
    app: ticketingworker
spec:
  replicas: 1
  selector:
    matchLabels:
        app: ticketingworker
  template:
    metadata:
      name: ticketingworker
      labels:
        app: ticketingworker
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: ticketingworker
        image: denhamparry/ticketing.worker:latest
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "kubernetes"
        volumeMounts:
        - name: secrets
          mountPath: /app/appsettings.kubernetes.json
          subPath: appsettings.kubernetes.json
        resources:
          requests:
            memory: "32Mi"
            cpu: "1m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      - name: ticketingworkerapi
        image: denhamparry/ticketing.worker.api:latest
        env:
        - name: ValueFromKubernetesEnvVariable
          valueFrom:
            configMapKeyRef:
              name: ticketingapi-configmap
              key: ValueFromKubernetesEnvVariable
        - name: ValueOverride
          valueFrom:
            configMapKeyRef:
              name: ticketingapi-configmap
              key: ValueOverride
        - name: MessagingQueue
          valueFrom:
            configMapKeyRef:
              name: ticketingapi-configmap
              key: MessagingQueue
        - name: MessagingUsername
          valueFrom:
            configMapKeyRef:
              name: ticketingapi-configmap
              key: MessagingUsername
        - name: MessagingPassword
          valueFrom:
            configMapKeyRef:
              name: ticketingapi-configmap
              key: MessagingPassword
        - name: ConnectionStrings__Messaging
          valueFrom:
            configMapKeyRef:
              name: ticketingapi-configmap
              key: Messaging
        - name: ConnectionStrings__TicketingDb
          valueFrom:
            configMapKeyRef:
              name: ticketingapi-configmap
              key: TicketingDb
        - name: ValueFromKubernetesSecret
          valueFrom:
            secretKeyRef:
              name: ticketingapi-secret
              key: ValueFromKubernetesSecret
        volumeMounts:
        - name: secrets
          mountPath: /app/appsettings.kubernetes.json
          subPath: appsettings.kubernetes.json
        resources:
          requests:
            memory: "32Mi"
            cpu: "1m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      volumes:
      - name: secrets
        secret:
          secretName: ticketingworker-appsettings
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler