---
apiVersion: v1
kind: Service
metadata:
  name: ticketingworker
  labels:
    app: ticketingworker
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: ticketingworker
---